import { useState } from "react";
import "./ExportReport.css";

interface ExportSettings {
  temperature: number;
  use_thinking: boolean;
  web_search_enabled: boolean;
  rag_enabled: boolean;
  model: string;
}

interface ExportStep {
  step_number: number;
  type: string;
  question?: string;
  llm_response?: string;
  tokens_used?: number;
  duration_ms?: number;
}

interface ExportData {
  workspace: string;
  prompt: string;
  response: string;
  settings: ExportSettings;
  steps?: ExportStep[];
  tokens_used?: number;
  latency_ms?: number;
  sources?: { title: string; url: string }[];
  timestamp: string;
}

interface ExportReportProps {
  isOpen: boolean;
  onClose: () => void;
  data: ExportData | null;
}

export default function ExportReport({ isOpen, onClose, data }: ExportReportProps) {
  const [exportFormat, setExportFormat] = useState<"markdown" | "json">("markdown");

  if (!isOpen || !data) return null;

  const generateMarkdown = (): string => {
    const lines: string[] = [];
    
    lines.push(`# Experiment Report`);
    lines.push(``);
    lines.push(`**Workspace:** ${formatWorkspace(data.workspace)}`);
    lines.push(`**Date:** ${new Date(data.timestamp).toLocaleString()}`);
    lines.push(``);
    
    lines.push(`## Settings`);
    lines.push(``);
    lines.push(`| Setting | Value |`);
    lines.push(`|---------|-------|`);
    lines.push(`| Model | ${data.settings.model || "Default"} |`);
    lines.push(`| Temperature | ${data.settings.temperature} |`);
    lines.push(`| Chain of Thought | ${data.settings.use_thinking ? "✅ Enabled" : "❌ Disabled"} |`);
    lines.push(`| Web Search | ${data.settings.web_search_enabled ? "✅ Enabled" : "❌ Disabled"} |`);
    lines.push(`| RAG | ${data.settings.rag_enabled ? "✅ Enabled" : "❌ Disabled"} |`);
    lines.push(``);
    
    lines.push(`## Prompt`);
    lines.push(``);
    lines.push("```");
    lines.push(data.prompt);
    lines.push("```");
    lines.push(``);
    
    if (data.steps && data.steps.length > 0) {
      lines.push(`## Thinking Process`);
      lines.push(``);
      data.steps.forEach((step, idx) => {
        lines.push(`### Step ${idx + 1}: ${step.type}`);
        if (step.question) {
          lines.push(`**Question:** ${step.question}`);
        }
        if (step.llm_response) {
          lines.push(``);
          lines.push(step.llm_response);
        }
        if (step.tokens_used || step.duration_ms) {
          lines.push(``);
          lines.push(`*${step.tokens_used ? `${step.tokens_used} tokens` : ""}${step.tokens_used && step.duration_ms ? " · " : ""}${step.duration_ms ? `${step.duration_ms}ms` : ""}*`);
        }
        lines.push(``);
      });
    }
    
    lines.push(`## Response`);
    lines.push(``);
    lines.push(data.response);
    lines.push(``);
    
    if (data.sources && data.sources.length > 0) {
      lines.push(`## Sources`);
      lines.push(``);
      data.sources.forEach((src) => {
        lines.push(`- [${src.title}](${src.url})`);
      });
      lines.push(``);
    }
    
    lines.push(`## Metrics`);
    lines.push(``);
    if (data.tokens_used) {
      lines.push(`- **Tokens Used:** ${data.tokens_used.toLocaleString()}`);
    }
    if (data.latency_ms) {
      lines.push(`- **Latency:** ${(data.latency_ms / 1000).toFixed(2)}s`);
    }
    lines.push(``);
    lines.push(`---`);
    lines.push(`*Generated by Nexa Thinking Framework*`);
    
    return lines.join("\n");
  };

  const generateJSON = (): string => {
    return JSON.stringify({
      workspace: data.workspace,
      timestamp: data.timestamp,
      prompt: data.prompt,
      response: data.response,
      settings: data.settings,
      steps: data.steps,
      metrics: {
        tokens_used: data.tokens_used,
        latency_ms: data.latency_ms,
      },
      sources: data.sources,
    }, null, 2);
  };

  const formatWorkspace = (workspace: string): string => {
    switch (workspace) {
      case "chain_of_thought": return "Chain of Thought";
      case "research_lab": return "Research Lab";
      case "project_manager": return "Project Manager";
      default: return workspace;
    }
  };

  const handleExport = () => {
    const content = exportFormat === "markdown" ? generateMarkdown() : generateJSON();
    const mimeType = exportFormat === "markdown" ? "text/markdown" : "application/json";
    const extension = exportFormat === "markdown" ? "md" : "json";
    
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `experiment-report-${new Date().toISOString().slice(0, 10)}.${extension}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyToClipboard = async () => {
    const content = exportFormat === "markdown" ? generateMarkdown() : generateJSON();
    await navigator.clipboard.writeText(content);
    alert("Copied to clipboard!");
  };

  const previewContent = exportFormat === "markdown" ? generateMarkdown() : generateJSON();

  return (
    <div className="export-report-overlay" onClick={onClose}>
      <div className="export-report-modal" onClick={(e) => e.stopPropagation()}>
        <div className="export-report-header">
          <div className="header-title">
            <span className="header-icon">📊</span>
            <h2>Export Experiment Report</h2>
          </div>
          <button className="close-btn" onClick={onClose} type="button">✕</button>
        </div>

        <div className="export-report-toolbar">
          <div className="format-selector">
            <label>Export Format:</label>
            <div className="format-buttons">
              <button
                className={`format-btn ${exportFormat === "markdown" ? "active" : ""}`}
                onClick={() => setExportFormat("markdown")}
                type="button"
              >
                📝 Markdown
              </button>
              <button
                className={`format-btn ${exportFormat === "json" ? "active" : ""}`}
                onClick={() => setExportFormat("json")}
                type="button"
              >
                {"{ }"} JSON
              </button>
            </div>
          </div>

          <div className="export-actions">
            <button className="action-btn copy" onClick={handleCopyToClipboard} type="button">
              📋 Copy
            </button>
            <button className="action-btn download" onClick={handleExport} type="button">
              📥 Download
            </button>
          </div>
        </div>

        <div className="export-report-content">
          <pre className="preview-content">{previewContent}</pre>
        </div>
      </div>
    </div>
  );
}

export function useExportReport() {
  const [isOpen, setIsOpen] = useState(false);
  const [exportData, setExportData] = useState<ExportData | null>(null);

  const openExport = (data: ExportData) => {
    setExportData(data);
    setIsOpen(true);
  };

  const closeExport = () => {
    setIsOpen(false);
  };

  return { isOpen, exportData, openExport, closeExport };
}
